In [1]:
import pandas as pd

In [2]:
# From Python List

Data = [["Karan",20,98],["Vishal",58,85],["Arjun",23,99],["Rahul",21,78]]

In [3]:
Data

[['Karan', 20, 98], ['Vishal', 58, 85], ['Arjun', 23, 99], ['Rahul', 21, 78]]

In [4]:
df = pd.DataFrame(Data, columns=["Name","Roll.No","Marks"])

In [5]:
df

     Name  Roll.No  Marks
0   Karan       20     98
1  Vishal       58     85
2   Arjun       23     99
3   Rahul       21     78

In [6]:
# DataFrame -2D Labeled Table

Company = {
    "Name" : ["Google","Microsoft","TCS","Wipro","HCL"],
    "Rateing" : [9.9,9.8,9.7,9.6,9.5],
    "City" : ["Kolkata","Delhi","Hyd","Jharkhand","Mumbai"]
}

In [7]:
df = pd.DataFrame(Company)

In [8]:
df

        Name  Rateing       City
0     Google      9.9    Kolkata
1  Microsoft      9.8      Delhi
2        TCS      9.7        Hyd
3      Wipro      9.6  Jharkhand
4        HCL      9.5     Mumbai

In [9]:
# From Dictionary List.

Data = {"Karan" : [20,23,52] , "Vishal" : [19,18,17]}
print(Data)

{'Karan': [20, 23, 52], 'Vishal': [19, 18, 17]}

In [10]:
df = pd.DataFrame(Data)

In [11]:
df

   Karan  Vishal
0     20      19
1     23      18
2     52      17

In [12]:
import numpy as np

In [13]:
# Numpy array.
arr = np.array([[100,200],[252,323]])
df = pd.DataFrame(arr, columns=["karan","Arjun"])
print(df)

   karan  Arjun
0    100    200
1    252    323

In [14]:
# From Excel Files:-

df = pd.read_excel("Data.xlsx")

In [15]:
df

     Name  School  Marks Section  Roll.No
0   Karan     DAV     98       A       23
1   Vishal    BTA     95       B       20
2    Arjun   DEFF     96       A       21
3  Avinash    BTS     91       A       52
4    Rahul   Deff     56       B       65
5   Ramesh    SCP     34       B       42
6    Kunal    DPS     41       B       23
7   Roshan    BNT     45       A       59

In [16]:
df = pd.read_csv("Data.csv")

In [17]:
df

     Name  School  Marks
0   Karan     DAV     98
1   Vishal    BTA     95
2    Arjun   DEFF     96
3  Avinash    BTS     91

In [18]:
df = pd.read_json("Data.json")

In [19]:
df

     Name    lang
0   Karan  Python
1  Vishal    Java

In [20]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [21]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]